### ISSUE TITLE
Can't output /ur refill command

### ISSUE THREAD

**Issue by finniespin** [MakuraYami/factorio-unlimited-resources#1]
Hi,

I've opened up my github account so you can get push notifications.

Regarding topic on mods.factorio.com:
https://mods.factorio.com/mods/barrykun/Unlimited-Resources/discussion/9068

Hereby a screenshot of my issue also!
http://imgur.com/a/rJJVh

I've opened to lua console as instructed via the wiki. Both "/ur" and "/ur refill" don
https://guides.github.com/features/mastering-markdown/'t seem to be working. I've also tried "/c ur refill" (all w/o quotes). I've tested in your new 1.03 version as well with no luck.

Am I missing something :s

Thank you again for putting effort into this

**Comment by MakuraYami** [comment]
Hi, it appears the code in the function was outdated and the command used to call it incorrect, I've updated both. the command is `/c remote.call('ur', 'refill')`

Thanks for your patience and interest in using my mod :)

**Comment by finniespin** [comment]
Hey,

Sorry for the long wait!
It's currently working again.

Thank you so much. I will close this issue.

Have a nice day.
